// File generated by the Firebase CLI.
// https://github.com/firebase/flutterfire_cli
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A platform-agnostic Firebase configuration
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_0M5vOJOAvADMCtqUJUQH8bRWqceo-4U',
    appId: '1:173701397724:web:ddedd1d778f1c53bb98819',
    messagingSenderId: '173701397724',
    projectId: 'shopease-d0cee',
    authDomain: 'shopease-d0cee.firebaseapp.com',
    storageBucket: 'shopease-d0cee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_0M5vOJOAvADMCtqUJUQH8bRWqceo-4U',
    appId: '1:173701397724:android:ddedd1d778f1c53bb98819',
    messagingSenderId: '173701397724',
    projectId: 'shopease-d0cee',
    storageBucket: 'shopease-d0cee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_0M5vOJOAvADMCtqUJUQH8bRWqceo-4U',
    appId: '1:173701397724:ios:ddedd1d778f1c53bb98819',
    messagingSenderId: '173701397724',
    projectId: 'shopease-d0cee',
    storageBucket: 'shopease-d0cee.firebasestorage.app',
    iosBundleId: 'com.shopease.mobile',
  );
}
